from oembed.tests.tests.consumer import *
from oembed.tests.tests.models import *
from oembed.tests.tests.parsers import *
from oembed.tests.tests.providers import *
from oembed.tests.tests.resources import *
from oembed.tests.tests.sites import *
from oembed.tests.tests.templatetags import *
from oembed.tests.tests.utils import *
from oembed.tests.tests.views import *
